apiVersion: v2
appVersion: 1.22.0
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x
description: Helm chart to deploy Conduktor Console on Kubernetes
home: https://www.conduktor.io
icon: https://www.conduktor.io/svgs/logo/symbol.svg
maintainers:
- email: support@conduktor.io
  name: Conduktor
  url: https://docs.conduktor.io/platform
name: console
sources:
- https://github.com/conduktor/conduktor-public-charts/tree/main/charts/console
version: 1.7.2
